baseURL = 'https://huxulm.github.io'
title = "LC灵神题解"
theme="archie"
copyright = "© LC"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

theme = "archie"
[params]
    math = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    style = 'monokailight'
    tabWidth = 4