baseURL = 'https://huxulm.github.io'
title = "LC灵神题解"
theme="archie"
copyright = "© LC"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
timeZone = "Asia/Shanghai"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "所有题解"
url = "/posts"
weight = 2

theme = "archie"
[params]
paginates = 50
paginatePath = "ppg"
math = true
search = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokailight'
    tabWidth = 4
